### ISSUE TITLE
Not working under nodejs14?

### ISSUE THREAD

**Issue by mararrdeveloper** [pinojs/pino-pretty#322] opened 2022-04-03 17:32 UTC
Hi there, 

On my PC pino-pretty is not printing anything in the terminal. I've used it before in another project under nodejs10 and it worked smoothly. Is it possible nodejs14 is not supported yet?

![image](https://user-images.githubusercontent.com/54005064/161440502-8fbf675c-7188-4f58-a6c7-8cd44ccf4217.png)

**Comment by mcollina** [comment] 2022-04-03 18:36
Are you using powershell? Looks like a duplicate of https://github.com/pinojs/pino-pretty/issues/173.

**Comment by mararrdeveloper** [comment] 2022-04-04 20:44
No, I've used the old terminal. Also using the programmatic approach results in the same problem (log not printed)

**Closed** 2022-08-17 10:47 UTC
