### ISSUE TITLE
Doesn't work with Powershell

### ISSUE THREAD

**Issue by Lukas-Sturm** [pinojs/pino-pretty#173] opened 2021-04-01 14:39 UTC
Hello there,

I tried using pino-pretty using Powershell:

Running inside a Powershell
`node .\program.js`
Results in my pino output

Running inside a Powershell
`node .\program.js | pino-pretty`
Results in no output

Running inside CMD
`node .\program.js | pino-pretty`
Results in formatted output

Running inside Powershell
`pino-pretty` then pasting the unformatted pino log 
Results in a formatted output

Changing the Encoding to UTF as stated [here](https://stackoverflow.com/questions/66904779/cmd-pipe-different-form-powershell-pipe/66905220) does not change anything.

pretty-pino is installed globally 
pino-pretty@4.7.1
pino is project based
pino@6.11.2

I am running PowerShell 7.1.3

**Comment by mcollina** [comment] 2021-04-01 16:55
I have no clue on how to help, I do not have time right now to spin up my old Windows machine.

**Comment by simoneb** [comment] 2021-04-09 12:41
I tried to reproduce it and TL;DR is powershell handles the pipe operator in ways that this will not work. I did not come to the root cause but I believe it should simply be avoided. This SO answer is very thorough and may provide an explanation into why it happens: https://stackoverflow.com/a/59118502/32093.

What I tried is a simple program:

```js
const log = require('pino')()

setInterval(() => log.info('hello world'), 1000)
```

And a package.json like this:

```json
"start": "node . | pino-pretty"
```

Running these commands in Powershell:

- `npm start`: works perfectly fine. I believe this may be because even though the npm script is run from Powershell, it actually spawns another shell where the pipe operator works in normal ways
- `node . | pino-pretty` never works with all variations of:
  - globally installed pino-pretty
  - locally installed pino-pretty
  - explicit .cmd and .ps1 pino-pretty file extensions and full paths

Which led me to conclude that Powershell is doing something fancy with the pipe operator that will prevent this from working. So the suggestion is to use a npm script instead and avoid the Powershell pipe altogether.

**Comment by jsumners** [comment] 2021-04-09 13:04
I am closing this as unsupported. Powershell is a foreign environment as relative to the "unix-like" environment that `pino-pretty` (and, really, the Node ecosystem as a whole) expects.

**Closed by jsumners** 2021-04-09 13:04 UTC
Labels: help wanted

**Comment by Lukas-Sturm** [comment] 2021-04-09 13:44
Thanks for looking into it.

For anyone interested in how I am kinda running it inside powershell.
I just cheat and start it using CMD
```
  "scripts": {
    "dev-win": "cmd.exe /c \"node .\\dist\\GameNode.js | pino-pretty\"",
    "dev-unix": "node ./dist/GameNode.js | pino-pretty"
  },
```

Works totally fine :)
